name: "Set Apio RELEASE_INFO"
description: "Set the RELEASE_INFO string with release info."

inputs:
  repo_path:
    description: "Relative path from the current working directory to the file containing RELEASE_DATE (e.g. apio/__init__.py)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Update RELEASE_INFO using Python
      shell: python
      run: |
        import datetime
        import sys
        import re
        from pathlib import Path

        target_file = Path("${{ inputs.repo_path }}") / "apio" / "__init__.py"

        if not target_file.is_file():
            print(f"Error: File not found: {target_file.resolve()}")
            exit(1)

        today = datetime.date.today()
        new_line = f"RELEASE_INFO = ({today.year}, {today.month}, {today.day})"

        content = target_file.read_text(encoding="utf-8")

        # Permissive pattern: matches RELEASE_INFO = (anything,anything,anything)
        # No requirement for spaces around values or commas
        pattern = r'RELEASE_INFO\s*=\s*\([^,)]+,[^,)]+,[^,)]+\)'

        match = re.search(pattern, content)
        if not match:
            print(f"Warning: No RELEASE_INFO tuple found in {target_file} - no change made")
            exit(1)
        else:
            old_match = match.group(0)
            updated = re.sub(pattern, new_line, content, count=1)
            target_file.write_text(updated, encoding="utf-8")
            print(f"Replaced '{old_match}' with '{new_line}' in {target_file}")

    - name: Cat modified file
      shell: bash
      run: |
        set -x
        cat -n "${{inputs.repo_path}}/apio/__init__.py"
